### ISSUE TITLE
image file is truncated (11 bytes not processed)

### ISSUE THREAD

**Issue by enchanted-sword** [HexCodeFFF/captionbot#18] opened 2021-04-05 16:26 UTC
OSError: image file is truncated (11 bytes not processed)

!sus is broken

![image](https://user-images.githubusercontent.com/81981111/113597957-d27e4380-9612-11eb-80a9-4ee5147eeefa.png)

Error log:
DATETIME:2021-04-05 11:23:37.401185
COMMAND:$sus when the adventure is bizzare!
TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 51, in pass_temp_session
    result = fn(*args, **kwargs)
  File "/home/hex/Desktop/captionbot/sus.py", line 91, in sus
    letter = master_im.crop((x_coords[0], 0, x_coords[1], y_coord_split))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1127, in crop
    self.load()
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 259, in load
    raise OSError(
OSError: image file is truncated (11 bytes not processed)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1000, in jermatext
    await improcess(ctx, sus.sus, [], text)
  File "main.py", line 320, in improcess
    raise e
  File "main.py", line 304, in improcess
    result = await renderpool.submit(func, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 70, in submit
    return await fut
OSError: image file is truncated (11 bytes not processed)

**Comment by HexCodeFFF** [comment] 2021-04-05 19:51
Duplicate of #14

**Comment by HexCodeFFF** [comment] 2021-04-09 16:45
![image](https://user-images.githubusercontent.com/35177464/114213655-e4b8f400-9928-11eb-9583-152670d1ff4b.png)
damn she wasnt lying, that image file can is truncated (11 bytes not processed)

**Comment by HexCodeFFF** [comment] 2021-04-20 19:03
![image](https://user-images.githubusercontent.com/35177464/115450142-27a88080-a1e1-11eb-8b04-a94288acac6e.png)
im seething with anger

**Comment by HexCodeFFF** [comment] 2021-04-20 21:08
closed in 37f6ab8

**Closed by HexCodeFFF** 2021-04-20 21:08 UTC
Labels: bug, duplicate
